
version: '3.8'

services:

  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    volumes:
      - etcd-data:/etcd-data
    ports:
      - "2379:2379" # Porta cliente padrão
      - "2380:2380" # Porta peer
    command:
      - /usr/local/bin/etcd
      - --data-dir=/etcd-data
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://etcd:2379
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster-token=etcd-cluster-1
      - --initial-cluster=node1=http://etcd:2380
      - --initial-cluster-state=new
    environment:
      ETCD_NAME: node1
    networks:
      - backend

  mysql_databases:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 172983456
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./go_zero_mysql_init_db.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./zrpc/go_zero_mysql_init_table.sql:/docker-entrypoint-initdb.d/02_init.sql
    networks:
      - backend

  redis:
    image: redis:6.0
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - backend

#  zrpc:
#    build:
#      context: .
#      dockerfile: ./zrpc/Dockerfile
#    ports:
#      - "8080:8080"
#    networks:
#      - backend

networks:
  backend:

volumes:
  mysql-data:
  redis-data:
  etcd-data:

