// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.19.4
// source: protos/zrpc.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ZrpcRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ZrpcRequest) Reset() {
	*x = ZrpcRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_zrpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZrpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZrpcRequest) ProtoMessage() {}

func (x *ZrpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_zrpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZrpcRequest.ProtoReflect.Descriptor instead.
func (*ZrpcRequest) Descriptor() ([]byte, []int) {
	return file_protos_zrpc_proto_rawDescGZIP(), []int{0}
}

type ZrpcResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ZrpcResponse) Reset() {
	*x = ZrpcResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_zrpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZrpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZrpcResponse) ProtoMessage() {}

func (x *ZrpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_zrpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZrpcResponse.ProtoReflect.Descriptor instead.
func (*ZrpcResponse) Descriptor() ([]byte, []int) {
	return file_protos_zrpc_proto_rawDescGZIP(), []int{1}
}

func (x *ZrpcResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_protos_zrpc_proto protoreflect.FileDescriptor

var file_protos_zrpc_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x7a, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x7a, 0x72, 0x70, 0x63, 0x22, 0x0d, 0x0a, 0x0b, 0x5a, 0x72, 0x70,
	0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x20, 0x0a, 0x0c, 0x5a, 0x72, 0x70, 0x63,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0x42, 0x0a, 0x0b, 0x5a, 0x72,
	0x70, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x33, 0x0a, 0x0a, 0x5a, 0x72, 0x70,
	0x63, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x11, 0x2e, 0x7a, 0x72, 0x70, 0x63, 0x2e, 0x5a,
	0x72, 0x70, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x7a, 0x72, 0x70,
	0x63, 0x2e, 0x5a, 0x72, 0x70, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x04,
	0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_zrpc_proto_rawDescOnce sync.Once
	file_protos_zrpc_proto_rawDescData = file_protos_zrpc_proto_rawDesc
)

func file_protos_zrpc_proto_rawDescGZIP() []byte {
	file_protos_zrpc_proto_rawDescOnce.Do(func() {
		file_protos_zrpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_zrpc_proto_rawDescData)
	})
	return file_protos_zrpc_proto_rawDescData
}

var file_protos_zrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_zrpc_proto_goTypes = []interface{}{
	(*ZrpcRequest)(nil),  // 0: zrpc.ZrpcRequest
	(*ZrpcResponse)(nil), // 1: zrpc.ZrpcResponse
}
var file_protos_zrpc_proto_depIdxs = []int32{
	0, // 0: zrpc.ZrpcService.ZrpcMethod:input_type -> zrpc.ZrpcRequest
	1, // 1: zrpc.ZrpcService.ZrpcMethod:output_type -> zrpc.ZrpcResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_zrpc_proto_init() }
func file_protos_zrpc_proto_init() {
	if File_protos_zrpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_zrpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZrpcRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_zrpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZrpcResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_zrpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_zrpc_proto_goTypes,
		DependencyIndexes: file_protos_zrpc_proto_depIdxs,
		MessageInfos:      file_protos_zrpc_proto_msgTypes,
	}.Build()
	File_protos_zrpc_proto = out.File
	file_protos_zrpc_proto_rawDesc = nil
	file_protos_zrpc_proto_goTypes = nil
	file_protos_zrpc_proto_depIdxs = nil
}
