// Code generated by goctl. DO NOT EDIT.
// Source: zrpc.proto

package server

import (
	"context"

	"go-zero-mysql-aula/common/pb"
	"go-zero-mysql-aula/zrpc/internal/logic"
	"go-zero-mysql-aula/zrpc/internal/svc"
)

type ZrpcServiceServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedZrpcServiceServer
}

func NewZrpcServiceServer(svcCtx *svc.ServiceContext) *ZrpcServiceServer {
	return &ZrpcServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ZrpcServiceServer) ZrpcMethod(ctx context.Context, in *__.ZrpcRequest) (*__.ZrpcResponse, error) {
	l := logic.NewZrpcMethodLogic(ctx, s.svcCtx)
	return l.ZrpcMethod(in)
}
